name: The Tor Project Blog
title: The Tor Project Blog
email: contact@torproject.org
description: > # this means to ignore newlines until "baseurl:"
  Tor community recent news and updates
baseurl: ""
url: "http://torblog.lan"
twitter_username: jekyllrb
github_username:  jekyll

markdown: redcarpet
highlighter: "pygments"
permalink: date

paginate: 5
paginate_path: "page:num"
paginate_category: "blog"

sass:
  sass_dir: _sass
  style: :compressed

jekyll-archives:
  layout: 'archive'
  enabled:
    - year
    - month
    - tags
  layouts:
    year: 'archive-year'
    month: 'archive-month'
    tag: 'archive-tag-and-category'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    tag: '/archive/tag/:name/'

gems:
  - jekyll-archives
  - jekyll-sitemap
